base: extend abc1276 to our CustomFaceProvider
* fixes -->

frameworks/base/services/core/java/com/android/server/biometrics/sensors/face/custom/CustomFaceProvider.java:87: error: CustomFaceProvider is not abstract and does not override abstract method cancelEnrollment(int,IBinder,long) in ServiceProvider
public class CustomFaceProvider implements ServiceProvider {
       ^
frameworks/base/services/core/java/com/android/server/biometrics/sensors/face/custom/CustomFaceProvider.java:295: error: scheduleEnroll(int,IBinder,byte[],int,IFaceServiceReceiver,String,int[],Surface,boolean) in CustomFaceProvider cannot implement scheduleEnroll(int,IBinder,byte[],int,IFaceServiceReceiver,String,int[],Surface,boolean) in ServiceProvider
    public void scheduleEnroll(int sensorId, IBinder token, byte[] hardwareAuthToken, int userId, IFaceServiceReceiver receiver, String opPackageName, int[] disabledFeatures, Surface previewSurface, boolean debugConsent) {
                ^
  return type void is not compatible with long
frameworks/base/services/core/java/com/android/server/biometrics/sensors/face/custom/CustomFaceProvider.java:294: error: method does not override or implement a method from a supertype
    @OverRide
    ^
frameworks/base/services/core/java/com/android/server/biometrics/sensors/face/custom/CustomFaceProvider.java:320: error: method does not override or implement a method from a supertype
    @OverRide
    ^
frameworks/base/services/core/java/com/android/server/biometrics/sensors/face/custom/CustomFaceProvider.java:322: error: method cancelEnrollment in class BiometricScheduler cannot be applied to given types;
        mHandler.post(() -> mScheduler.cancelEnrollment(token));
                                      ^
  required: IBinder,long
  found: IBinder
  reason: actual and formal argument lists differ in length

Signed-off-by: aswin7469 <aswinas@pixysos.com>
Change-Id: Idc4560662e8f93d9503bb4dd82ff9e034414477b